### ISSUE TITLE
Cloud Version not working

### ISSUE THREAD

**Issue by shakiralynch1** [nfield0/PlayMetrix#33]
Newest version of cloud deployment only displays this 

**URGENT!**

<img width="551" alt="image" src="https://github.com/nfield0/PlayMetrix/assets/92158341/79211694-948b-41aa-848b-cd6b9be2eb86">

**Comment by nfield0** [comment]
![image](https://github.com/nfield0/PlayMetrix/assets/92158821/2d2648b3-84d1-46bb-ae30-6e0942fbd11a)
Attending Players is broken

**Comment by begleyboy600** [comment]
> ![image](https://private-user-images.githubusercontent.com/92158821/320270280-2d2648b3-84d1-46bb-ae30-6e0942fbd11a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODM4NDMsIm5iZiI6MTcxMjQ4MzU0MywicGF0aCI6Ii85MjE1ODgyMS8zMjAyNzAyODAtMmQyNjQ4YjMtODRkMS00NmJiLWFlMzAtNmUwOTQyZmJkMTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA5NTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMWMyYzU5OTIwNjk0N2FiY2ExNWNmMTk5YzUyMjJhN2E5ZDk0Yzc1OTI3ODZiZDU5MDU2YjY2NWFhM2MxMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C81gZjZ6jdeVySiRC2e2L-ECcIekeUUlZsoENYjO8r8) Attending Players is broken

I checked the database on the cloud and the player_attending is set to NULL for some reason

**Comment by nfield0** [comment]
> > ![image](https://private-user-images.githubusercontent.com/92158821/320270280-2d2648b3-84d1-46bb-ae30-6e0942fbd11a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODM4NDMsIm5iZiI6MTcxMjQ4MzU0MywicGF0aCI6Ii85MjE1ODgyMS8zMjAyNzAyODAtMmQyNjQ4YjMtODRkMS00NmJiLWFlMzAtNmUwOTQyZmJkMTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA5NTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMWMyYzU5OTIwNjk0N2FiY2ExNWNmMTk5YzUyMjJhN2E5ZDk0Yzc1OTI3ODZiZDU5MDU2YjY2NWFhM2MxMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C81gZjZ6jdeVySiRC2e2L-ECcIekeUUlZsoENYjO8r8) Attending Players is broken
> 
> I checked the database on the cloud and the player_attending is set to NULL for some reason

Luana requested new schedules have an attending value of Null, maybe it has not been updated in frontend? @luanakimley

**Comment by begleyboy600** [comment]
Did everything else work ok?

**Comment by begleyboy600** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/92158821/320270280-2d2648b3-84d1-46bb-ae30-6e0942fbd11a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODM4NDMsIm5iZiI6MTcxMjQ4MzU0MywicGF0aCI6Ii85MjE1ODgyMS8zMjAyNzAyODAtMmQyNjQ4YjMtODRkMS00NmJiLWFlMzAtNmUwOTQyZmJkMTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA5NTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMWMyYzU5OTIwNjk0N2FiY2ExNWNmMTk5YzUyMjJhN2E5ZDk0Yzc1OTI3ODZiZDU5MDU2YjY2NWFhM2MxMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C81gZjZ6jdeVySiRC2e2L-ECcIekeUUlZsoENYjO8r8) Attending Players is broken
> > 
> > 
> > I checked the database on the cloud and the player_attending is set to NULL for some reason
> 
> Luana requested new schedules have an attending value of Null, maybe it has not been updated in frontend? @luanakimley

check the request logs on the cloud, and looks like the backend responses are grand:
<img width="644" alt="image" src="https://github.com/nfield0/PlayMetrix/assets/36737067/6b3860fb-cea8-4b57-9687-f811251ff811">
